[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "espnet>=202304",
    "espnet-model-zoo>=0.1.7",
    "numpy>=2.2.5",
    "torchaudio>=2.7.0",
    "transformers>=4.51.3",
]